### ISSUE TITLE
Add help for runtimeObjects

### ISSUE THREAD

**Issue by imago-storm** [electric-cloud-community/EC-DSLIDE#19]
_From @lrochette on August 22, 2016 17:17_

it would be nice to get the list of attributes for runtimeObjects like pipelineRuntime.
It may not be possible if those are not exposed in the DSL itself.

I guess we need to check with @urvashisingh 

_Copied from original issue: electric-cloud/EC-DSLIDE#34_

**Comment by gmaxey** [comment]
The "Attribute Explorer" example can be used to do this.

`evalScript flowRuntimeId : "fdd324a3-3e8b-11e9-83d7-08002792342c", value : '''\
  function getKeyPairs(obj)
  {
      var res = [];
      for(var m in obj) {
              res.push(m + ":" + obj[m])
      }
      return res;
  }

getKeyPairs(myFlowRuntime).join("\\n")`

Returns all the runtime properties
