### ISSUE TITLE
Response window data truncated

### ISSUE THREAD

**Issue by imago-storm** [electric-cloud-community/EC-DSLIDE#27]
_From @gmaxey on April 16, 2018 14:39_

![image](https://user-images.githubusercontent.com/1416096/38815626-5e865452-4162-11e8-8f86-762b01e08701.png)

_Copied from original issue: electric-cloud/EC-DSLIDE#45_

**Comment by gmaxey** [comment]
This can be fixed by setting lineWrapping to false in "var resultWindow" definition
