### ISSUE TITLE
Move customization out of CodeMirror directory

### ISSUE THREAD

**Issue by imago-storm** [electric-cloud-community/EC-DSLIDE#5]
_From @gmaxey on August 31, 2015 22:13_

_Copied from original issue: electric-cloud/EC-DSLIDE#8_

**Comment by imago-storm** [comment]
_From @gmaxey on August 31, 2015 22:14_

Is it possible to move all DSLIDE content out of CodeMirror? That way we don't have to contribute enhancements back to MIT.

**Comment by gmaxey** [comment]
Done with version 1.5.3
